[package]
name = "waymark-fn-main-common"
edition = "2024"
version.workspace = true
publish.workspace = true

[dependencies]
waymark-managed-spawner-supervised = { workspace = true }

color-eyre = { workspace = true }
envfury = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
