[package]
name = "waymark-workflow-completion-convert-proto"
version.workspace = true
publish.workspace = true
edition = "2024"

[dependencies]
waymark-convert-core = { workspace = true }
waymark-proto = { workspace = true }
waymark-proto-python-value-conversions = { workspace = true }
waymark-vm-runtime-exception = { workspace = true }
waymark-vm-value-convert-core = { workspace = true }
waymark-vm-value-convert-proto = { workspace = true }
waymark-vm-value-python = { workspace = true }
waymark-workflow-completion-core = { workspace = true }

[lib]
doctest = false
