[package]
name = "waymark-vm-compiler-for-ast-old-const-value"
edition = "2024"
version.workspace = true
publish.workspace = true

[dependencies]
waymark-vm-ast-old = { workspace = true }
waymark-vm-value-python = { workspace = true }

serde = { workspace = true, optional = true }
thiserror = { workspace = true }
typed_floats = { workspace = true }

[features]
serde = [
  "dep:serde",
  "serde/derive",
  "waymark-vm-value-python/serde",
]
