[package]
name = "waymark-vm-driver"
edition = "2024"
version.workspace = true
publish.workspace = true

[dependencies]
waymark-vm-executable = { workspace = true }
waymark-vm-interpreter = { workspace = true }
waymark-vm-runtime = { workspace = true }
waymark-vm-runtime-core = { workspace = true }
waymark-vm-runtime-effect = { workspace = true }
waymark-vm-runtime-exception = { workspace = true }
waymark-vm-runtime-promise-core = { workspace = true }

tokio = { workspace = true, features = ["sync"] }
tracing = { workspace = true }

[dev-dependencies]
waymark-vm-runtime-test = { workspace = true }

tokio = { workspace = true, features = ["macros", "rt", "sync"] }
