[advisories]
ignore = []

[licenses]
allow = [
  "Apache-2.0",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "BSL-1.0",
  "ISC",
  "MIT",
  "MPL-2.0",
  "OpenSSL",
  "Unicode-3.0",
  "Unicode-DFS-2016",
  "Zlib",
]
confidence-threshold = 0.8

[licenses.private]
ignore = true
registries = []

[bans]
multiple-versions = "allow"
wildcards = "allow"

[bans.workspace-dependencies]
duplicates = "deny"
include-path-dependencies = true
unused = "deny"

[[bans.deny]]
name = "async-trait"
reason = "use GAT-based traits, avoid legacy async-trait"
wrappers = ["axum", "axum-core", "tonic"]

[[bans.deny]]
name = "tracing-subscriber"
use-instead = "waymark-fn-main-common"
reason = "do not redo the base fn main setup manually"
wrappers = [
  "waymark-fn-main-common",
  "waymark-observability-setup",
  "console-subscriber",
  "tracing-chrome",
  "tracing-error",
]

[[bans.deny]]
name = "uuid"
use-instead = "waymark-ids"
reason = "you should use waymark-ids for the IDs; if this is not what you need it for - add your crate to wrappers below"
wrappers = ["waymark-ids", "sqlx-core", "sqlx-postgres", "waymark-dag"]

[sources]
unknown-registry = "warn"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
