# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: action.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 5, 29, 0, "", "action.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b"\n\x0c\x61\x63tion.proto\x12\x0ewaymark.action*i\n\rActionRuntime\x12\x1e\n\x1a\x41\x43TION_RUNTIME_UNSPECIFIED\x10\x00\x12\x19\n\x15\x41\x43TION_RUNTIME_PYTHON\x10\x01\x12\x1d\n\x19\x41\x43TION_RUNTIME_JAVASCRIPT\x10\x02\x62\x06proto3"
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "action_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_ACTIONRUNTIME"]._serialized_start = 32
    _globals["_ACTIONRUNTIME"]._serialized_end = 137
# @@protoc_insertion_point(module_scope)
