"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import sys
import typing

import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _ActionRuntime:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _ActionRuntimeEnumTypeWrapper(
    google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ActionRuntime.ValueType],
    builtins.type,
):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    ACTION_RUNTIME_UNSPECIFIED: _ActionRuntime.ValueType  # 0
    ACTION_RUNTIME_PYTHON: _ActionRuntime.ValueType  # 1
    ACTION_RUNTIME_JAVASCRIPT: _ActionRuntime.ValueType  # 2

class ActionRuntime(_ActionRuntime, metaclass=_ActionRuntimeEnumTypeWrapper):
    """Runtime required to execute an action."""

ACTION_RUNTIME_UNSPECIFIED: ActionRuntime.ValueType  # 0
ACTION_RUNTIME_PYTHON: ActionRuntime.ValueType  # 1
ACTION_RUNTIME_JAVASCRIPT: ActionRuntime.ValueType  # 2
Global___ActionRuntime: typing_extensions.TypeAlias = ActionRuntime
