"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import sys
import typing

import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import google.protobuf.struct_pb2

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class WorkflowArgumentValue(google.protobuf.message.Message):
    """=============================================================================
    The Python flavor's encoded values
    =============================================================================
    The encoding of a single Python workflow value, carried as
    the opaque `value` bytes of the framing-level
    `waymark.messages.WorkflowArgument`.  Python-specific by design — a
    value never crosses a language boundary in this form, so only the Python
    flavor's own codecs read or write these messages.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PRIMITIVE_FIELD_NUMBER: builtins.int
    BASEMODEL_FIELD_NUMBER: builtins.int
    EXCEPTION_FIELD_NUMBER: builtins.int
    LIST_VALUE_FIELD_NUMBER: builtins.int
    TUPLE_VALUE_FIELD_NUMBER: builtins.int
    DICT_VALUE_FIELD_NUMBER: builtins.int
    @property
    def primitive(self) -> Global___PrimitiveWorkflowArgument: ...
    @property
    def basemodel(self) -> Global___BaseModelWorkflowArgument: ...
    @property
    def exception(self) -> Global___WorkflowExceptionValue: ...
    @property
    def list_value(self) -> Global___WorkflowListArgument: ...
    @property
    def tuple_value(self) -> Global___WorkflowTupleArgument: ...
    @property
    def dict_value(self) -> Global___WorkflowDictArgument: ...
    def __init__(
        self,
        *,
        primitive: Global___PrimitiveWorkflowArgument | None = ...,
        basemodel: Global___BaseModelWorkflowArgument | None = ...,
        exception: Global___WorkflowExceptionValue | None = ...,
        list_value: Global___WorkflowListArgument | None = ...,
        tuple_value: Global___WorkflowTupleArgument | None = ...,
        dict_value: Global___WorkflowDictArgument | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing.Literal[
            "basemodel",
            b"basemodel",
            "dict_value",
            b"dict_value",
            "exception",
            b"exception",
            "kind",
            b"kind",
            "list_value",
            b"list_value",
            "primitive",
            b"primitive",
            "tuple_value",
            b"tuple_value",
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "basemodel",
            b"basemodel",
            "dict_value",
            b"dict_value",
            "exception",
            b"exception",
            "kind",
            b"kind",
            "list_value",
            b"list_value",
            "primitive",
            b"primitive",
            "tuple_value",
            b"tuple_value",
        ],
    ) -> None: ...
    def WhichOneof(
        self, oneof_group: typing.Literal["kind", b"kind"]
    ) -> (
        typing.Literal[
            "primitive", "basemodel", "exception", "list_value", "tuple_value", "dict_value"
        ]
        | None
    ): ...

Global___WorkflowArgumentValue: typing_extensions.TypeAlias = WorkflowArgumentValue

@typing.final
class PrimitiveWorkflowArgument(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STRING_VALUE_FIELD_NUMBER: builtins.int
    DOUBLE_VALUE_FIELD_NUMBER: builtins.int
    INT_VALUE_FIELD_NUMBER: builtins.int
    BOOL_VALUE_FIELD_NUMBER: builtins.int
    NULL_VALUE_FIELD_NUMBER: builtins.int
    string_value: builtins.str
    double_value: builtins.float
    int_value: builtins.int
    bool_value: builtins.bool
    null_value: google.protobuf.struct_pb2.NullValue.ValueType
    def __init__(
        self,
        *,
        string_value: builtins.str = ...,
        double_value: builtins.float = ...,
        int_value: builtins.int = ...,
        bool_value: builtins.bool = ...,
        null_value: google.protobuf.struct_pb2.NullValue.ValueType = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing.Literal[
            "bool_value",
            b"bool_value",
            "double_value",
            b"double_value",
            "int_value",
            b"int_value",
            "kind",
            b"kind",
            "null_value",
            b"null_value",
            "string_value",
            b"string_value",
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "bool_value",
            b"bool_value",
            "double_value",
            b"double_value",
            "int_value",
            b"int_value",
            "kind",
            b"kind",
            "null_value",
            b"null_value",
            "string_value",
            b"string_value",
        ],
    ) -> None: ...
    def WhichOneof(
        self, oneof_group: typing.Literal["kind", b"kind"]
    ) -> (
        typing.Literal["string_value", "double_value", "int_value", "bool_value", "null_value"]
        | None
    ): ...

Global___PrimitiveWorkflowArgument: typing_extensions.TypeAlias = PrimitiveWorkflowArgument

@typing.final
class BaseModelWorkflowArgument(google.protobuf.message.Message):
    """Pydantic BaseModel or similar structured types"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MODULE_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    module: builtins.str
    name: builtins.str
    @property
    def data(self) -> Global___WorkflowDictArgument: ...
    def __init__(
        self,
        *,
        module: builtins.str = ...,
        name: builtins.str = ...,
        data: Global___WorkflowDictArgument | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["data", b"data"]) -> builtins.bool: ...
    def ClearField(
        self, field_name: typing.Literal["data", b"data", "module", b"module", "name", b"name"]
    ) -> None: ...

Global___BaseModelWorkflowArgument: typing_extensions.TypeAlias = BaseModelWorkflowArgument

@typing.final
class ActionResultValue(google.protobuf.message.Message):
    """How an action call completed, in this language's terms: the value the
    action returned, or the exception it raised.

    The distinction lives here rather than in the transport framing
    because it is a language notion: not every language has an
    exception-like construct, and each decides for itself what completing
    a call can look like.

    Both arms carry values; what separates them is the state the VM
    settles the awaiting promise in. An exception in the `value` arm is an
    ordinary returned value — returning an exception is not raising it.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VALUE_FIELD_NUMBER: builtins.int
    EXCEPTION_FIELD_NUMBER: builtins.int
    @property
    def value(self) -> Global___WorkflowArgumentValue: ...
    @property
    def exception(self) -> Global___WorkflowExceptionValue: ...
    def __init__(
        self,
        *,
        value: Global___WorkflowArgumentValue | None = ...,
        exception: Global___WorkflowExceptionValue | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing.Literal[
            "exception", b"exception", "outcome", b"outcome", "value", b"value"
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "exception", b"exception", "outcome", b"outcome", "value", b"value"
        ],
    ) -> None: ...
    def WhichOneof(
        self, oneof_group: typing.Literal["outcome", b"outcome"]
    ) -> typing.Literal["value", "exception"] | None: ...

Global___ActionResultValue: typing_extensions.TypeAlias = ActionResultValue

@typing.final
class WorkflowExceptionValue(google.protobuf.message.Message):
    """A raised exception, shaped as the VM models one: the type identifying
    it, and the details value carried alongside.

    The details are an ordinary value — in practice a dict carrying the
    language-specific particulars (module, message, traceback, the
    exception's own values, the class hierarchy for `except` matching).
    Nothing about those particulars is wire-level structure: they are just
    what this language chose to put in the details.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TYPE_ID_FIELD_NUMBER: builtins.int
    DETAILS_FIELD_NUMBER: builtins.int
    type_id: builtins.str
    @property
    def details(self) -> Global___WorkflowArgumentValue: ...
    def __init__(
        self,
        *,
        type_id: builtins.str = ...,
        details: Global___WorkflowArgumentValue | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["details", b"details"]) -> builtins.bool: ...
    def ClearField(
        self, field_name: typing.Literal["details", b"details", "type_id", b"type_id"]
    ) -> None: ...

Global___WorkflowExceptionValue: typing_extensions.TypeAlias = WorkflowExceptionValue

@typing.final
class WorkflowListArgument(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ITEMS_FIELD_NUMBER: builtins.int
    @property
    def items(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        Global___WorkflowArgumentValue
    ]: ...
    def __init__(
        self,
        *,
        items: collections.abc.Iterable[Global___WorkflowArgumentValue] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["items", b"items"]) -> None: ...

Global___WorkflowListArgument: typing_extensions.TypeAlias = WorkflowListArgument

@typing.final
class WorkflowTupleArgument(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ITEMS_FIELD_NUMBER: builtins.int
    @property
    def items(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        Global___WorkflowArgumentValue
    ]: ...
    def __init__(
        self,
        *,
        items: collections.abc.Iterable[Global___WorkflowArgumentValue] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["items", b"items"]) -> None: ...

Global___WorkflowTupleArgument: typing_extensions.TypeAlias = WorkflowTupleArgument

@typing.final
class WorkflowDictEntry(google.protobuf.message.Message):
    """A dictionary entry inside an encoded value — structural, unlike the
    framing-level `waymark.messages.WorkflowArgument`.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    KEY_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    key: builtins.str
    @property
    def value(self) -> Global___WorkflowArgumentValue: ...
    def __init__(
        self,
        *,
        key: builtins.str = ...,
        value: Global___WorkflowArgumentValue | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["value", b"value"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

Global___WorkflowDictEntry: typing_extensions.TypeAlias = WorkflowDictEntry

@typing.final
class WorkflowDictArgument(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ENTRIES_FIELD_NUMBER: builtins.int
    @property
    def entries(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        Global___WorkflowDictEntry
    ]: ...
    def __init__(
        self,
        *,
        entries: collections.abc.Iterable[Global___WorkflowDictEntry] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["entries", b"entries"]) -> None: ...

Global___WorkflowDictArgument: typing_extensions.TypeAlias = WorkflowDictArgument
