"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import sys
import typing

import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import google.protobuf.struct_pb2

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Value(google.protobuf.message.Message):
    """=============================================================================
    The Python flavor's encoded values
    =============================================================================
    The encoding of Python workflow values and the four per-language seam
    messages carrying them (`WorkflowArguments`, `ActionArguments`,
    `ActionOutcome`, `WorkflowOutcome`), each travelling as one opaque
    payload at the transport framing level.  Python-specific by design — a
    value never crosses a language boundary in this form, so only the Python
    flavor's own codecs read or write these messages.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PRIMITIVE_FIELD_NUMBER: builtins.int
    BASEMODEL_FIELD_NUMBER: builtins.int
    EXCEPTION_FIELD_NUMBER: builtins.int
    LIST_VALUE_FIELD_NUMBER: builtins.int
    TUPLE_VALUE_FIELD_NUMBER: builtins.int
    DICT_VALUE_FIELD_NUMBER: builtins.int
    @property
    def primitive(self) -> Global___PrimitiveValue: ...
    @property
    def basemodel(self) -> Global___BaseModelValue: ...
    @property
    def exception(self) -> Global___ExceptionValue: ...
    @property
    def list_value(self) -> Global___ListValue: ...
    @property
    def tuple_value(self) -> Global___TupleValue: ...
    @property
    def dict_value(self) -> Global___DictValue: ...
    def __init__(
        self,
        *,
        primitive: Global___PrimitiveValue | None = ...,
        basemodel: Global___BaseModelValue | None = ...,
        exception: Global___ExceptionValue | None = ...,
        list_value: Global___ListValue | None = ...,
        tuple_value: Global___TupleValue | None = ...,
        dict_value: Global___DictValue | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing.Literal[
            "basemodel",
            b"basemodel",
            "dict_value",
            b"dict_value",
            "exception",
            b"exception",
            "kind",
            b"kind",
            "list_value",
            b"list_value",
            "primitive",
            b"primitive",
            "tuple_value",
            b"tuple_value",
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "basemodel",
            b"basemodel",
            "dict_value",
            b"dict_value",
            "exception",
            b"exception",
            "kind",
            b"kind",
            "list_value",
            b"list_value",
            "primitive",
            b"primitive",
            "tuple_value",
            b"tuple_value",
        ],
    ) -> None: ...
    def WhichOneof(
        self, oneof_group: typing.Literal["kind", b"kind"]
    ) -> (
        typing.Literal[
            "primitive", "basemodel", "exception", "list_value", "tuple_value", "dict_value"
        ]
        | None
    ): ...

Global___Value: typing_extensions.TypeAlias = Value

@typing.final
class PrimitiveValue(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STRING_VALUE_FIELD_NUMBER: builtins.int
    DOUBLE_VALUE_FIELD_NUMBER: builtins.int
    INT_VALUE_FIELD_NUMBER: builtins.int
    BOOL_VALUE_FIELD_NUMBER: builtins.int
    NULL_VALUE_FIELD_NUMBER: builtins.int
    string_value: builtins.str
    double_value: builtins.float
    int_value: builtins.int
    bool_value: builtins.bool
    null_value: google.protobuf.struct_pb2.NullValue.ValueType
    def __init__(
        self,
        *,
        string_value: builtins.str = ...,
        double_value: builtins.float = ...,
        int_value: builtins.int = ...,
        bool_value: builtins.bool = ...,
        null_value: google.protobuf.struct_pb2.NullValue.ValueType = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing.Literal[
            "bool_value",
            b"bool_value",
            "double_value",
            b"double_value",
            "int_value",
            b"int_value",
            "kind",
            b"kind",
            "null_value",
            b"null_value",
            "string_value",
            b"string_value",
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "bool_value",
            b"bool_value",
            "double_value",
            b"double_value",
            "int_value",
            b"int_value",
            "kind",
            b"kind",
            "null_value",
            b"null_value",
            "string_value",
            b"string_value",
        ],
    ) -> None: ...
    def WhichOneof(
        self, oneof_group: typing.Literal["kind", b"kind"]
    ) -> (
        typing.Literal["string_value", "double_value", "int_value", "bool_value", "null_value"]
        | None
    ): ...

Global___PrimitiveValue: typing_extensions.TypeAlias = PrimitiveValue

@typing.final
class BaseModelValue(google.protobuf.message.Message):
    """Pydantic BaseModel or similar structured types"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MODULE_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    module: builtins.str
    name: builtins.str
    @property
    def data(self) -> Global___DictValue: ...
    def __init__(
        self,
        *,
        module: builtins.str = ...,
        name: builtins.str = ...,
        data: Global___DictValue | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["data", b"data"]) -> builtins.bool: ...
    def ClearField(
        self, field_name: typing.Literal["data", b"data", "module", b"module", "name", b"name"]
    ) -> None: ...

Global___BaseModelValue: typing_extensions.TypeAlias = BaseModelValue

@typing.final
class ActionOutcome(google.protobuf.message.Message):
    """How an action call completed, in this language's terms: the value the
    action returned, or the exception it raised.

    The distinction lives here rather than in the transport framing
    because it is a language notion: not every language has an
    exception-like construct, and each decides for itself what completing
    a call can look like.

    Both arms carry values; what separates them is the state the VM
    settles the awaiting promise in. An exception in the `value` arm is an
    ordinary returned value — returning an exception is not raising it.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VALUE_FIELD_NUMBER: builtins.int
    EXCEPTION_FIELD_NUMBER: builtins.int
    @property
    def value(self) -> Global___Value: ...
    @property
    def exception(self) -> Global___ExceptionValue: ...
    def __init__(
        self,
        *,
        value: Global___Value | None = ...,
        exception: Global___ExceptionValue | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing.Literal[
            "exception", b"exception", "outcome", b"outcome", "value", b"value"
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "exception", b"exception", "outcome", b"outcome", "value", b"value"
        ],
    ) -> None: ...
    def WhichOneof(
        self, oneof_group: typing.Literal["outcome", b"outcome"]
    ) -> typing.Literal["value", "exception"] | None: ...

Global___ActionOutcome: typing_extensions.TypeAlias = ActionOutcome

@typing.final
class WorkflowOutcome(google.protobuf.message.Message):
    """How a workflow instance completed, in this language's terms: the value
    the workflow returned, or the exception that ended it.

    The server -> client counterpart of `ActionOutcome`, kept separate
    because the two planes can diverge independently. The completion value
    travels as-is: user data is never mistaken for framing, whatever shape
    it takes.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VALUE_FIELD_NUMBER: builtins.int
    EXCEPTION_FIELD_NUMBER: builtins.int
    @property
    def value(self) -> Global___Value: ...
    @property
    def exception(self) -> Global___ExceptionValue: ...
    def __init__(
        self,
        *,
        value: Global___Value | None = ...,
        exception: Global___ExceptionValue | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing.Literal[
            "exception", b"exception", "outcome", b"outcome", "value", b"value"
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "exception", b"exception", "outcome", b"outcome", "value", b"value"
        ],
    ) -> None: ...
    def WhichOneof(
        self, oneof_group: typing.Literal["outcome", b"outcome"]
    ) -> typing.Literal["value", "exception"] | None: ...

Global___WorkflowOutcome: typing_extensions.TypeAlias = WorkflowOutcome

@typing.final
class WorkflowArguments(google.protobuf.message.Message):
    """The arguments a workflow instance starts with, in this language's
    terms: named values, in the order the caller gave them.

    One of the four per-language seam types (with `ActionArguments`,
    `ActionOutcome`, and `WorkflowOutcome`); the whole set travels as one
    opaque payload at the framing level, so the framing knows neither the
    values nor the shape of the argument list.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ARGUMENTS_FIELD_NUMBER: builtins.int
    @property
    def arguments(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        Global___WorkflowArgument
    ]: ...
    def __init__(
        self,
        *,
        arguments: collections.abc.Iterable[Global___WorkflowArgument] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["arguments", b"arguments"]) -> None: ...

Global___WorkflowArguments: typing_extensions.TypeAlias = WorkflowArguments

@typing.final
class WorkflowArgument(google.protobuf.message.Message):
    """One named workflow argument. Structural — never crosses a conversion
    boundary on its own; only the enclosing `WorkflowArguments` does.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    KEY_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    key: builtins.str
    @property
    def value(self) -> Global___Value: ...
    def __init__(
        self,
        *,
        key: builtins.str = ...,
        value: Global___Value | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["value", b"value"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

Global___WorkflowArgument: typing_extensions.TypeAlias = WorkflowArgument

@typing.final
class ActionArguments(google.protobuf.message.Message):
    """The arguments of one action call, in this language's terms: named
    values, in the order the calling convention paired them.

    The client -> worker counterpart of `WorkflowArguments`, kept
    separate because the two planes can diverge independently — the
    calling convention (positional-to-named pairing, dependency-marker
    omission) is this seam's own.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ARGUMENTS_FIELD_NUMBER: builtins.int
    @property
    def arguments(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        Global___ActionArgument
    ]: ...
    def __init__(
        self,
        *,
        arguments: collections.abc.Iterable[Global___ActionArgument] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["arguments", b"arguments"]) -> None: ...

Global___ActionArguments: typing_extensions.TypeAlias = ActionArguments

@typing.final
class ActionArgument(google.protobuf.message.Message):
    """One named action-call argument. Structural — never crosses a
    conversion boundary on its own; only the enclosing `ActionArguments`
    does.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    KEY_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    key: builtins.str
    @property
    def value(self) -> Global___Value: ...
    def __init__(
        self,
        *,
        key: builtins.str = ...,
        value: Global___Value | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["value", b"value"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

Global___ActionArgument: typing_extensions.TypeAlias = ActionArgument

@typing.final
class ExceptionValue(google.protobuf.message.Message):
    """A raised exception, shaped as the VM models one: the type identifying
    it, and the details value carried alongside.

    The details are an ordinary value — in practice a dict carrying the
    language-specific particulars (module, message, traceback, the
    exception's own values, the class hierarchy for `except` matching).
    Nothing about those particulars is wire-level structure: they are just
    what this language chose to put in the details.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TYPE_ID_FIELD_NUMBER: builtins.int
    DETAILS_FIELD_NUMBER: builtins.int
    type_id: builtins.str
    @property
    def details(self) -> Global___Value: ...
    def __init__(
        self,
        *,
        type_id: builtins.str = ...,
        details: Global___Value | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["details", b"details"]) -> builtins.bool: ...
    def ClearField(
        self, field_name: typing.Literal["details", b"details", "type_id", b"type_id"]
    ) -> None: ...

Global___ExceptionValue: typing_extensions.TypeAlias = ExceptionValue

@typing.final
class ListValue(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ITEMS_FIELD_NUMBER: builtins.int
    @property
    def items(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___Value]: ...
    def __init__(
        self,
        *,
        items: collections.abc.Iterable[Global___Value] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["items", b"items"]) -> None: ...

Global___ListValue: typing_extensions.TypeAlias = ListValue

@typing.final
class TupleValue(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ITEMS_FIELD_NUMBER: builtins.int
    @property
    def items(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___Value]: ...
    def __init__(
        self,
        *,
        items: collections.abc.Iterable[Global___Value] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["items", b"items"]) -> None: ...

Global___TupleValue: typing_extensions.TypeAlias = TupleValue

@typing.final
class DictEntry(google.protobuf.message.Message):
    """A dictionary entry inside an encoded value — structural, unlike the
    framing-level `waymark.messages.WorkflowArgument`.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    KEY_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    key: builtins.str
    @property
    def value(self) -> Global___Value: ...
    def __init__(
        self,
        *,
        key: builtins.str = ...,
        value: Global___Value | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["value", b"value"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

Global___DictEntry: typing_extensions.TypeAlias = DictEntry

@typing.final
class DictValue(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ENTRIES_FIELD_NUMBER: builtins.int
    @property
    def entries(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        Global___DictEntry
    ]: ...
    def __init__(
        self,
        *,
        entries: collections.abc.Iterable[Global___DictEntry] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["entries", b"entries"]) -> None: ...

Global___DictValue: typing_extensions.TypeAlias = DictValue
