[package]
name = "waymark-ir-parser"
version.workspace = true
publish.workspace = true
edition = "2024"

[dependencies]
waymark-action-core = { workspace = true }
waymark-proto = { workspace = true }
waymark-vm-ast-old-proto-helpers = { workspace = true }

regex = { workspace = true }

[lib]
test = false
doctest = false
