[package]
name = "waymark-fullset-effect-handler"
edition = "2024"
version.workspace = true
publish.workspace = true

[dependencies]
waymark-vm-driver-core = { workspace = true }
waymark-vm-interpreter-coreset = { workspace = true }
waymark-vm-interpreter-extcallset = { workspace = true }
waymark-vm-interpreter-fullset = { workspace = true }
waymark-vm-runtime-effect = { workspace = true }

thiserror = { workspace = true }
