[package]
name = "waymark-python-workflow-ir-reader"
edition = "2024"
version.workspace = true
publish.workspace = true

[dependencies]
waymark-proto = { workspace = true }

prost = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["process"] }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
