[package]
name = "waymark-vm-compiler-for-ast-old"
edition = "2024"
version.workspace = true
publish.workspace = true

[dependencies]
waymark-vm-ast-old = { workspace = true }
waymark-vm-bytecode = { workspace = true }
waymark-vm-bytecode-core = { workspace = true }
waymark-vm-compiler-for-ast-old-core = { workspace = true }
waymark-vm-instructions-coreset = { workspace = true }
waymark-vm-instructions-excset = { workspace = true }
waymark-vm-instructions-extcallset = { workspace = true }
waymark-vm-instructions-fullset = { workspace = true }
waymark-vm-instructions-pureset = { workspace = true }
waymark-vm-runtime-core = { workspace = true }

index_type = { workspace = true }
nonempty-collections = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
waymark-nonzero-duration = { workspace = true }
waymark-support-test-python = { workspace = true }
waymark-vm-ast-old-fmt = { workspace = true }
waymark-vm-ast-old-helpers = { workspace = true }
waymark-vm-bytecode-fmt = { workspace = true }
waymark-vm-compiler-for-ast-old-test-support = { workspace = true }
waymark-vm-interpreter-coreset = { workspace = true }
waymark-vm-interpreter-extcallset = { workspace = true }
waymark-vm-interpreter-fullset = { workspace = true }
waymark-vm-runtime = { workspace = true }
waymark-vm-runtime-exception = { workspace = true }

async-walkdir = { workspace = true }
futures-util = { workspace = true }
insta = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
