[package]
name = "waymark-vm-value-convert-proto"
edition = "2024"
version.workspace = true
publish.workspace = true

[dependencies]
waymark-convert-core = { workspace = true }
waymark-proto = { workspace = true }
waymark-vm-runtime-exception = { workspace = true }
waymark-vm-value-convert-core = { workspace = true }
waymark-vm-value-python = { workspace = true }

indexmap = { workspace = true }
typed_floats = { workspace = true }

[dev-dependencies]
waymark-vm-runtime-promise-core = { workspace = true }

[lib]
doctest = false
