[package]
name = "waymark-vm-interpreter-coreset"
edition = "2024"
version.workspace = true
publish.workspace = true

[dependencies]
waymark-blanket-impl-macros = { workspace = true }
waymark-vm-executable = { workspace = true }
waymark-vm-instructions-coreset = { workspace = true }
waymark-vm-interpreter = { workspace = true }
waymark-vm-runtime-core = { workspace = true }
waymark-vm-runtime-exception = { workspace = true }
waymark-vm-runtime-promise-core = { workspace = true }

derive-where = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
waymark-vm-bytecode = { workspace = true }
waymark-vm-exception-handler = { workspace = true }
waymark-vm-interpreter-operations = { workspace = true }
waymark-vm-runtime = { workspace = true }
waymark-vm-runtime-test = { workspace = true }
waymark-vm-runtime-value = { workspace = true }
