[package]
name = "waymark-lossy-batcher"
edition = "2024"
version.workspace = true
publish.workspace = true

[dependencies]
waymark-nonzero-duration = { workspace = true }

futures-util = { workspace = true }
metrics = { workspace = true }
nonempty-collections = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["macros", "sync", "time"] }
tracing = { workspace = true }

[dev-dependencies]
metrics-util = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt", "sync", "test-util", "time"] }
