"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import sys
import typing

import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class SourceLocation(google.protobuf.message.Message):
    """-----------------------------------------------------------------------------
    Source Location Tracking
    -----------------------------------------------------------------------------
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LINENO_FIELD_NUMBER: builtins.int
    COL_OFFSET_FIELD_NUMBER: builtins.int
    END_LINENO_FIELD_NUMBER: builtins.int
    END_COL_OFFSET_FIELD_NUMBER: builtins.int
    lineno: builtins.int
    col_offset: builtins.int
    end_lineno: builtins.int
    end_col_offset: builtins.int
    def __init__(
        self,
        *,
        lineno: builtins.int = ...,
        col_offset: builtins.int = ...,
        end_lineno: builtins.int | None = ...,
        end_col_offset: builtins.int | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing.Literal[
            "_end_col_offset",
            b"_end_col_offset",
            "_end_lineno",
            b"_end_lineno",
            "end_col_offset",
            b"end_col_offset",
            "end_lineno",
            b"end_lineno",
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "_end_col_offset",
            b"_end_col_offset",
            "_end_lineno",
            b"_end_lineno",
            "col_offset",
            b"col_offset",
            "end_col_offset",
            b"end_col_offset",
            "end_lineno",
            b"end_lineno",
            "lineno",
            b"lineno",
        ],
    ) -> None: ...
    @typing.overload
    def WhichOneof(
        self, oneof_group: typing.Literal["_end_col_offset", b"_end_col_offset"]
    ) -> typing.Literal["end_col_offset"] | None: ...
    @typing.overload
    def WhichOneof(
        self, oneof_group: typing.Literal["_end_lineno", b"_end_lineno"]
    ) -> typing.Literal["end_lineno"] | None: ...

Global___SourceLocation: typing_extensions.TypeAlias = SourceLocation

@typing.final
class BackoffConfig(google.protobuf.message.Message):
    """-----------------------------------------------------------------------------
    Execution Policies
    -----------------------------------------------------------------------------
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _Kind:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _KindEnumTypeWrapper(
        google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[BackoffConfig._Kind.ValueType],
        builtins.type,
    ):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        KIND_UNSPECIFIED: BackoffConfig._Kind.ValueType  # 0
        KIND_LINEAR: BackoffConfig._Kind.ValueType  # 1
        KIND_EXPONENTIAL: BackoffConfig._Kind.ValueType  # 2

    class Kind(_Kind, metaclass=_KindEnumTypeWrapper): ...
    KIND_UNSPECIFIED: BackoffConfig.Kind.ValueType  # 0
    KIND_LINEAR: BackoffConfig.Kind.ValueType  # 1
    KIND_EXPONENTIAL: BackoffConfig.Kind.ValueType  # 2

    KIND_FIELD_NUMBER: builtins.int
    BASE_DELAY_MS_FIELD_NUMBER: builtins.int
    MULTIPLIER_FIELD_NUMBER: builtins.int
    kind: Global___BackoffConfig.Kind.ValueType
    base_delay_ms: builtins.int
    multiplier: builtins.float
    """Only for exponential"""
    def __init__(
        self,
        *,
        kind: Global___BackoffConfig.Kind.ValueType = ...,
        base_delay_ms: builtins.int = ...,
        multiplier: builtins.float | None = ...,
    ) -> None: ...
    def HasField(
        self, field_name: typing.Literal["_multiplier", b"_multiplier", "multiplier", b"multiplier"]
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "_multiplier",
            b"_multiplier",
            "base_delay_ms",
            b"base_delay_ms",
            "kind",
            b"kind",
            "multiplier",
            b"multiplier",
        ],
    ) -> None: ...
    def WhichOneof(
        self, oneof_group: typing.Literal["_multiplier", b"_multiplier"]
    ) -> typing.Literal["multiplier"] | None: ...

Global___BackoffConfig: typing_extensions.TypeAlias = BackoffConfig

@typing.final
class RunActionConfig(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TIMEOUT_SECONDS_FIELD_NUMBER: builtins.int
    MAX_RETRIES_FIELD_NUMBER: builtins.int
    BACKOFF_FIELD_NUMBER: builtins.int
    timeout_seconds: builtins.int
    max_retries: builtins.int
    @property
    def backoff(self) -> Global___BackoffConfig: ...
    def __init__(
        self,
        *,
        timeout_seconds: builtins.int | None = ...,
        max_retries: builtins.int | None = ...,
        backoff: Global___BackoffConfig | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing.Literal[
            "_backoff",
            b"_backoff",
            "_max_retries",
            b"_max_retries",
            "_timeout_seconds",
            b"_timeout_seconds",
            "backoff",
            b"backoff",
            "max_retries",
            b"max_retries",
            "timeout_seconds",
            b"timeout_seconds",
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "_backoff",
            b"_backoff",
            "_max_retries",
            b"_max_retries",
            "_timeout_seconds",
            b"_timeout_seconds",
            "backoff",
            b"backoff",
            "max_retries",
            b"max_retries",
            "timeout_seconds",
            b"timeout_seconds",
        ],
    ) -> None: ...
    @typing.overload
    def WhichOneof(
        self, oneof_group: typing.Literal["_backoff", b"_backoff"]
    ) -> typing.Literal["backoff"] | None: ...
    @typing.overload
    def WhichOneof(
        self, oneof_group: typing.Literal["_max_retries", b"_max_retries"]
    ) -> typing.Literal["max_retries"] | None: ...
    @typing.overload
    def WhichOneof(
        self, oneof_group: typing.Literal["_timeout_seconds", b"_timeout_seconds"]
    ) -> typing.Literal["timeout_seconds"] | None: ...

Global___RunActionConfig: typing_extensions.TypeAlias = RunActionConfig

@typing.final
class ActionCall(google.protobuf.message.Message):
    """-----------------------------------------------------------------------------
    Core IR Nodes
    -----------------------------------------------------------------------------

    A single action invocation - the fundamental unit of durable execution
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class KwargsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(
            self, field_name: typing.Literal["key", b"key", "value", b"value"]
        ) -> None: ...

    ACTION_FIELD_NUMBER: builtins.int
    MODULE_FIELD_NUMBER: builtins.int
    KWARGS_FIELD_NUMBER: builtins.int
    TARGET_FIELD_NUMBER: builtins.int
    CONFIG_FIELD_NUMBER: builtins.int
    LOCATION_FIELD_NUMBER: builtins.int
    action: builtins.str
    """Action name"""
    module: builtins.str
    """Module where action is defined"""
    target: builtins.str
    """Variable to assign result to"""
    @property
    def kwargs(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]:
        """Argument expressions as strings"""

    @property
    def config(self) -> Global___RunActionConfig: ...
    @property
    def location(self) -> Global___SourceLocation: ...
    def __init__(
        self,
        *,
        action: builtins.str = ...,
        module: builtins.str | None = ...,
        kwargs: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
        target: builtins.str | None = ...,
        config: Global___RunActionConfig | None = ...,
        location: Global___SourceLocation | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing.Literal[
            "_config",
            b"_config",
            "_location",
            b"_location",
            "_module",
            b"_module",
            "_target",
            b"_target",
            "config",
            b"config",
            "location",
            b"location",
            "module",
            b"module",
            "target",
            b"target",
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "_config",
            b"_config",
            "_location",
            b"_location",
            "_module",
            b"_module",
            "_target",
            b"_target",
            "action",
            b"action",
            "config",
            b"config",
            "kwargs",
            b"kwargs",
            "location",
            b"location",
            "module",
            b"module",
            "target",
            b"target",
        ],
    ) -> None: ...
    @typing.overload
    def WhichOneof(
        self, oneof_group: typing.Literal["_config", b"_config"]
    ) -> typing.Literal["config"] | None: ...
    @typing.overload
    def WhichOneof(
        self, oneof_group: typing.Literal["_location", b"_location"]
    ) -> typing.Literal["location"] | None: ...
    @typing.overload
    def WhichOneof(
        self, oneof_group: typing.Literal["_module", b"_module"]
    ) -> typing.Literal["module"] | None: ...
    @typing.overload
    def WhichOneof(
        self, oneof_group: typing.Literal["_target", b"_target"]
    ) -> typing.Literal["target"] | None: ...

Global___ActionCall: typing_extensions.TypeAlias = ActionCall

@typing.final
class Gather(google.protobuf.message.Message):
    """Parallel execution of multiple actions"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CALLS_FIELD_NUMBER: builtins.int
    TARGET_FIELD_NUMBER: builtins.int
    LOCATION_FIELD_NUMBER: builtins.int
    target: builtins.str
    """Variable to assign tuple result to"""
    @property
    def calls(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        Global___ActionCall
    ]: ...
    @property
    def location(self) -> Global___SourceLocation: ...
    def __init__(
        self,
        *,
        calls: collections.abc.Iterable[Global___ActionCall] | None = ...,
        target: builtins.str | None = ...,
        location: Global___SourceLocation | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing.Literal[
            "_location",
            b"_location",
            "_target",
            b"_target",
            "location",
            b"location",
            "target",
            b"target",
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "_location",
            b"_location",
            "_target",
            b"_target",
            "calls",
            b"calls",
            "location",
            b"location",
            "target",
            b"target",
        ],
    ) -> None: ...
    @typing.overload
    def WhichOneof(
        self, oneof_group: typing.Literal["_location", b"_location"]
    ) -> typing.Literal["location"] | None: ...
    @typing.overload
    def WhichOneof(
        self, oneof_group: typing.Literal["_target", b"_target"]
    ) -> typing.Literal["target"] | None: ...

Global___Gather: typing_extensions.TypeAlias = Gather

@typing.final
class PythonBlock(google.protobuf.message.Message):
    """Arbitrary Python code that doesn't contain actions (escape hatch)"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CODE_FIELD_NUMBER: builtins.int
    IMPORTS_FIELD_NUMBER: builtins.int
    DEFINITIONS_FIELD_NUMBER: builtins.int
    INPUTS_FIELD_NUMBER: builtins.int
    OUTPUTS_FIELD_NUMBER: builtins.int
    LOCATION_FIELD_NUMBER: builtins.int
    code: builtins.str
    @property
    def imports(
        self,
    ) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """Import statements needed"""

    @property
    def definitions(
        self,
    ) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """Function/class definitions needed"""

    @property
    def inputs(
        self,
    ) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """Variables read"""

    @property
    def outputs(
        self,
    ) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """Variables written"""

    @property
    def location(self) -> Global___SourceLocation: ...
    def __init__(
        self,
        *,
        code: builtins.str = ...,
        imports: collections.abc.Iterable[builtins.str] | None = ...,
        definitions: collections.abc.Iterable[builtins.str] | None = ...,
        inputs: collections.abc.Iterable[builtins.str] | None = ...,
        outputs: collections.abc.Iterable[builtins.str] | None = ...,
        location: Global___SourceLocation | None = ...,
    ) -> None: ...
    def HasField(
        self, field_name: typing.Literal["_location", b"_location", "location", b"location"]
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "_location",
            b"_location",
            "code",
            b"code",
            "definitions",
            b"definitions",
            "imports",
            b"imports",
            "inputs",
            b"inputs",
            "location",
            b"location",
            "outputs",
            b"outputs",
        ],
    ) -> None: ...
    def WhichOneof(
        self, oneof_group: typing.Literal["_location", b"_location"]
    ) -> typing.Literal["location"] | None: ...

Global___PythonBlock: typing_extensions.TypeAlias = PythonBlock

@typing.final
class Loop(google.protobuf.message.Message):
    """A for loop with action(s) in the body"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ITERATOR_EXPR_FIELD_NUMBER: builtins.int
    LOOP_VAR_FIELD_NUMBER: builtins.int
    ACCUMULATORS_FIELD_NUMBER: builtins.int
    PREAMBLE_FIELD_NUMBER: builtins.int
    BODY_FIELD_NUMBER: builtins.int
    YIELDS_FIELD_NUMBER: builtins.int
    LOCATION_FIELD_NUMBER: builtins.int
    iterator_expr: builtins.str
    """Expression producing the iterable"""
    loop_var: builtins.str
    """Loop variable name"""
    @property
    def accumulators(
        self,
    ) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """Variables initialized as [] before loop"""

    @property
    def preamble(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___PythonBlock]:
        """Pure Python before first action"""

    @property
    def body(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___ActionCall]:
        """Action calls in sequence"""

    @property
    def yields(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___YieldExpr]:
        """What gets collected each iteration"""

    @property
    def location(self) -> Global___SourceLocation: ...
    def __init__(
        self,
        *,
        iterator_expr: builtins.str = ...,
        loop_var: builtins.str = ...,
        accumulators: collections.abc.Iterable[builtins.str] | None = ...,
        preamble: collections.abc.Iterable[Global___PythonBlock] | None = ...,
        body: collections.abc.Iterable[Global___ActionCall] | None = ...,
        yields: collections.abc.Iterable[Global___YieldExpr] | None = ...,
        location: Global___SourceLocation | None = ...,
    ) -> None: ...
    def HasField(
        self, field_name: typing.Literal["_location", b"_location", "location", b"location"]
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "_location",
            b"_location",
            "accumulators",
            b"accumulators",
            "body",
            b"body",
            "iterator_expr",
            b"iterator_expr",
            "location",
            b"location",
            "loop_var",
            b"loop_var",
            "preamble",
            b"preamble",
            "yields",
            b"yields",
        ],
    ) -> None: ...
    def WhichOneof(
        self, oneof_group: typing.Literal["_location", b"_location"]
    ) -> typing.Literal["location"] | None: ...

Global___Loop: typing_extensions.TypeAlias = Loop

@typing.final
class YieldExpr(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SOURCE_EXPR_FIELD_NUMBER: builtins.int
    ACCUMULATOR_FIELD_NUMBER: builtins.int
    source_expr: builtins.str
    """Expression to evaluate"""
    accumulator: builtins.str
    """Accumulator to append to"""
    def __init__(
        self,
        *,
        source_expr: builtins.str = ...,
        accumulator: builtins.str = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing.Literal["accumulator", b"accumulator", "source_expr", b"source_expr"],
    ) -> None: ...

Global___YieldExpr: typing_extensions.TypeAlias = YieldExpr

@typing.final
class Branch(google.protobuf.message.Message):
    """One branch of a conditional"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    GUARD_FIELD_NUMBER: builtins.int
    PREAMBLE_FIELD_NUMBER: builtins.int
    ACTIONS_FIELD_NUMBER: builtins.int
    POSTAMBLE_FIELD_NUMBER: builtins.int
    LOCATION_FIELD_NUMBER: builtins.int
    guard: builtins.str
    """Guard expression (Python boolean expr)"""
    @property
    def preamble(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___PythonBlock]:
        """Statements before first action"""

    @property
    def actions(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___ActionCall]:
        """One or more actions (chained in DAG)"""

    @property
    def postamble(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___PythonBlock]:
        """Statements after last action"""

    @property
    def location(self) -> Global___SourceLocation: ...
    def __init__(
        self,
        *,
        guard: builtins.str = ...,
        preamble: collections.abc.Iterable[Global___PythonBlock] | None = ...,
        actions: collections.abc.Iterable[Global___ActionCall] | None = ...,
        postamble: collections.abc.Iterable[Global___PythonBlock] | None = ...,
        location: Global___SourceLocation | None = ...,
    ) -> None: ...
    def HasField(
        self, field_name: typing.Literal["_location", b"_location", "location", b"location"]
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "_location",
            b"_location",
            "actions",
            b"actions",
            "guard",
            b"guard",
            "location",
            b"location",
            "postamble",
            b"postamble",
            "preamble",
            b"preamble",
        ],
    ) -> None: ...
    def WhichOneof(
        self, oneof_group: typing.Literal["_location", b"_location"]
    ) -> typing.Literal["location"] | None: ...

Global___Branch: typing_extensions.TypeAlias = Branch

@typing.final
class Conditional(google.protobuf.message.Message):
    """If/elif/else with actions in each branch"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BRANCHES_FIELD_NUMBER: builtins.int
    TARGET_FIELD_NUMBER: builtins.int
    LOCATION_FIELD_NUMBER: builtins.int
    target: builtins.str
    """Common target variable if branches assign"""
    @property
    def branches(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___Branch]:
        """Must cover all cases (else required)"""

    @property
    def location(self) -> Global___SourceLocation: ...
    def __init__(
        self,
        *,
        branches: collections.abc.Iterable[Global___Branch] | None = ...,
        target: builtins.str | None = ...,
        location: Global___SourceLocation | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing.Literal[
            "_location",
            b"_location",
            "_target",
            b"_target",
            "location",
            b"location",
            "target",
            b"target",
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "_location",
            b"_location",
            "_target",
            b"_target",
            "branches",
            b"branches",
            "location",
            b"location",
            "target",
            b"target",
        ],
    ) -> None: ...
    @typing.overload
    def WhichOneof(
        self, oneof_group: typing.Literal["_location", b"_location"]
    ) -> typing.Literal["location"] | None: ...
    @typing.overload
    def WhichOneof(
        self, oneof_group: typing.Literal["_target", b"_target"]
    ) -> typing.Literal["target"] | None: ...

Global___Conditional: typing_extensions.TypeAlias = Conditional

@typing.final
class ExceptHandler(google.protobuf.message.Message):
    """An except handler"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    EXCEPTION_TYPES_FIELD_NUMBER: builtins.int
    BODY_FIELD_NUMBER: builtins.int
    LOCATION_FIELD_NUMBER: builtins.int
    @property
    def exception_types(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        Global___ExceptionType
    ]: ...
    @property
    def body(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        Global___ActionCall
    ]: ...
    @property
    def location(self) -> Global___SourceLocation: ...
    def __init__(
        self,
        *,
        exception_types: collections.abc.Iterable[Global___ExceptionType] | None = ...,
        body: collections.abc.Iterable[Global___ActionCall] | None = ...,
        location: Global___SourceLocation | None = ...,
    ) -> None: ...
    def HasField(
        self, field_name: typing.Literal["_location", b"_location", "location", b"location"]
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "_location",
            b"_location",
            "body",
            b"body",
            "exception_types",
            b"exception_types",
            "location",
            b"location",
        ],
    ) -> None: ...
    def WhichOneof(
        self, oneof_group: typing.Literal["_location", b"_location"]
    ) -> typing.Literal["location"] | None: ...

Global___ExceptHandler: typing_extensions.TypeAlias = ExceptHandler

@typing.final
class ExceptionType(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MODULE_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    module: builtins.str
    """e.g., "mymodule" for mymodule.MyError"""
    name: builtins.str
    """e.g., "ValueError" (None for bare except)"""
    def __init__(
        self,
        *,
        module: builtins.str | None = ...,
        name: builtins.str | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing.Literal[
            "_module", b"_module", "_name", b"_name", "module", b"module", "name", b"name"
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "_module", b"_module", "_name", b"_name", "module", b"module", "name", b"name"
        ],
    ) -> None: ...
    @typing.overload
    def WhichOneof(
        self, oneof_group: typing.Literal["_module", b"_module"]
    ) -> typing.Literal["module"] | None: ...
    @typing.overload
    def WhichOneof(
        self, oneof_group: typing.Literal["_name", b"_name"]
    ) -> typing.Literal["name"] | None: ...

Global___ExceptionType: typing_extensions.TypeAlias = ExceptionType

@typing.final
class TryExcept(google.protobuf.message.Message):
    """Try/except block with actions"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TRY_BODY_FIELD_NUMBER: builtins.int
    HANDLERS_FIELD_NUMBER: builtins.int
    LOCATION_FIELD_NUMBER: builtins.int
    @property
    def try_body(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        Global___ActionCall
    ]: ...
    @property
    def handlers(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        Global___ExceptHandler
    ]: ...
    @property
    def location(self) -> Global___SourceLocation: ...
    def __init__(
        self,
        *,
        try_body: collections.abc.Iterable[Global___ActionCall] | None = ...,
        handlers: collections.abc.Iterable[Global___ExceptHandler] | None = ...,
        location: Global___SourceLocation | None = ...,
    ) -> None: ...
    def HasField(
        self, field_name: typing.Literal["_location", b"_location", "location", b"location"]
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "_location",
            b"_location",
            "handlers",
            b"handlers",
            "location",
            b"location",
            "try_body",
            b"try_body",
        ],
    ) -> None: ...
    def WhichOneof(
        self, oneof_group: typing.Literal["_location", b"_location"]
    ) -> typing.Literal["location"] | None: ...

Global___TryExcept: typing_extensions.TypeAlias = TryExcept

@typing.final
class Sleep(google.protobuf.message.Message):
    """Durable sleep"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DURATION_EXPR_FIELD_NUMBER: builtins.int
    LOCATION_FIELD_NUMBER: builtins.int
    duration_expr: builtins.str
    """Duration in seconds (as expression string)"""
    @property
    def location(self) -> Global___SourceLocation: ...
    def __init__(
        self,
        *,
        duration_expr: builtins.str = ...,
        location: Global___SourceLocation | None = ...,
    ) -> None: ...
    def HasField(
        self, field_name: typing.Literal["_location", b"_location", "location", b"location"]
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "_location", b"_location", "duration_expr", b"duration_expr", "location", b"location"
        ],
    ) -> None: ...
    def WhichOneof(
        self, oneof_group: typing.Literal["_location", b"_location"]
    ) -> typing.Literal["location"] | None: ...

Global___Sleep: typing_extensions.TypeAlias = Sleep

@typing.final
class Return(google.protobuf.message.Message):
    """Return statement"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    EXPR_FIELD_NUMBER: builtins.int
    ACTION_FIELD_NUMBER: builtins.int
    GATHER_FIELD_NUMBER: builtins.int
    LOCATION_FIELD_NUMBER: builtins.int
    expr: builtins.str
    """Return a variable or expression"""
    @property
    def action(self) -> Global___ActionCall:
        """Return result of action call"""

    @property
    def gather(self) -> Global___Gather:
        """Return result of gather"""

    @property
    def location(self) -> Global___SourceLocation: ...
    def __init__(
        self,
        *,
        expr: builtins.str = ...,
        action: Global___ActionCall | None = ...,
        gather: Global___Gather | None = ...,
        location: Global___SourceLocation | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing.Literal[
            "_location",
            b"_location",
            "action",
            b"action",
            "expr",
            b"expr",
            "gather",
            b"gather",
            "location",
            b"location",
            "value",
            b"value",
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "_location",
            b"_location",
            "action",
            b"action",
            "expr",
            b"expr",
            "gather",
            b"gather",
            "location",
            b"location",
            "value",
            b"value",
        ],
    ) -> None: ...
    @typing.overload
    def WhichOneof(
        self, oneof_group: typing.Literal["_location", b"_location"]
    ) -> typing.Literal["location"] | None: ...
    @typing.overload
    def WhichOneof(
        self, oneof_group: typing.Literal["value", b"value"]
    ) -> typing.Literal["expr", "action", "gather"] | None: ...

Global___Return: typing_extensions.TypeAlias = Return

@typing.final
class Spread(google.protobuf.message.Message):
    """Compile-time expansion of action over collection
    Pattern: [await action(x=item) for item in collection]
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ACTION_FIELD_NUMBER: builtins.int
    LOOP_VAR_FIELD_NUMBER: builtins.int
    ITERABLE_FIELD_NUMBER: builtins.int
    TARGET_FIELD_NUMBER: builtins.int
    LOCATION_FIELD_NUMBER: builtins.int
    loop_var: builtins.str
    iterable: builtins.str
    """Variable name of collection"""
    target: builtins.str
    @property
    def action(self) -> Global___ActionCall:
        """Template action (kwargs reference loop_var)"""

    @property
    def location(self) -> Global___SourceLocation: ...
    def __init__(
        self,
        *,
        action: Global___ActionCall | None = ...,
        loop_var: builtins.str = ...,
        iterable: builtins.str = ...,
        target: builtins.str | None = ...,
        location: Global___SourceLocation | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing.Literal[
            "_location",
            b"_location",
            "_target",
            b"_target",
            "action",
            b"action",
            "location",
            b"location",
            "target",
            b"target",
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "_location",
            b"_location",
            "_target",
            b"_target",
            "action",
            b"action",
            "iterable",
            b"iterable",
            "location",
            b"location",
            "loop_var",
            b"loop_var",
            "target",
            b"target",
        ],
    ) -> None: ...
    @typing.overload
    def WhichOneof(
        self, oneof_group: typing.Literal["_location", b"_location"]
    ) -> typing.Literal["location"] | None: ...
    @typing.overload
    def WhichOneof(
        self, oneof_group: typing.Literal["_target", b"_target"]
    ) -> typing.Literal["target"] | None: ...

Global___Spread: typing_extensions.TypeAlias = Spread

@typing.final
class Statement(google.protobuf.message.Message):
    """-----------------------------------------------------------------------------
    Statement Union
    -----------------------------------------------------------------------------
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ACTION_CALL_FIELD_NUMBER: builtins.int
    GATHER_FIELD_NUMBER: builtins.int
    PYTHON_BLOCK_FIELD_NUMBER: builtins.int
    LOOP_FIELD_NUMBER: builtins.int
    CONDITIONAL_FIELD_NUMBER: builtins.int
    TRY_EXCEPT_FIELD_NUMBER: builtins.int
    SLEEP_FIELD_NUMBER: builtins.int
    RETURN_STMT_FIELD_NUMBER: builtins.int
    SPREAD_FIELD_NUMBER: builtins.int
    @property
    def action_call(self) -> Global___ActionCall: ...
    @property
    def gather(self) -> Global___Gather: ...
    @property
    def python_block(self) -> Global___PythonBlock: ...
    @property
    def loop(self) -> Global___Loop: ...
    @property
    def conditional(self) -> Global___Conditional: ...
    @property
    def try_except(self) -> Global___TryExcept: ...
    @property
    def sleep(self) -> Global___Sleep: ...
    @property
    def return_stmt(self) -> Global___Return: ...
    @property
    def spread(self) -> Global___Spread: ...
    def __init__(
        self,
        *,
        action_call: Global___ActionCall | None = ...,
        gather: Global___Gather | None = ...,
        python_block: Global___PythonBlock | None = ...,
        loop: Global___Loop | None = ...,
        conditional: Global___Conditional | None = ...,
        try_except: Global___TryExcept | None = ...,
        sleep: Global___Sleep | None = ...,
        return_stmt: Global___Return | None = ...,
        spread: Global___Spread | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing.Literal[
            "action_call",
            b"action_call",
            "conditional",
            b"conditional",
            "gather",
            b"gather",
            "kind",
            b"kind",
            "loop",
            b"loop",
            "python_block",
            b"python_block",
            "return_stmt",
            b"return_stmt",
            "sleep",
            b"sleep",
            "spread",
            b"spread",
            "try_except",
            b"try_except",
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "action_call",
            b"action_call",
            "conditional",
            b"conditional",
            "gather",
            b"gather",
            "kind",
            b"kind",
            "loop",
            b"loop",
            "python_block",
            b"python_block",
            "return_stmt",
            b"return_stmt",
            "sleep",
            b"sleep",
            "spread",
            b"spread",
            "try_except",
            b"try_except",
        ],
    ) -> None: ...
    def WhichOneof(
        self, oneof_group: typing.Literal["kind", b"kind"]
    ) -> (
        typing.Literal[
            "action_call",
            "gather",
            "python_block",
            "loop",
            "conditional",
            "try_except",
            "sleep",
            "return_stmt",
            "spread",
        ]
        | None
    ): ...

Global___Statement: typing_extensions.TypeAlias = Statement

@typing.final
class WorkflowParam(google.protobuf.message.Message):
    """-----------------------------------------------------------------------------
    Workflow Definition
    -----------------------------------------------------------------------------
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    TYPE_ANNOTATION_FIELD_NUMBER: builtins.int
    name: builtins.str
    type_annotation: builtins.str
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        type_annotation: builtins.str | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing.Literal[
            "_type_annotation", b"_type_annotation", "type_annotation", b"type_annotation"
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "_type_annotation",
            b"_type_annotation",
            "name",
            b"name",
            "type_annotation",
            b"type_annotation",
        ],
    ) -> None: ...
    def WhichOneof(
        self, oneof_group: typing.Literal["_type_annotation", b"_type_annotation"]
    ) -> typing.Literal["type_annotation"] | None: ...

Global___WorkflowParam: typing_extensions.TypeAlias = WorkflowParam

@typing.final
class Workflow(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    PARAMS_FIELD_NUMBER: builtins.int
    BODY_FIELD_NUMBER: builtins.int
    RETURN_TYPE_FIELD_NUMBER: builtins.int
    name: builtins.str
    return_type: builtins.str
    @property
    def params(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        Global___WorkflowParam
    ]: ...
    @property
    def body(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        Global___Statement
    ]: ...
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        params: collections.abc.Iterable[Global___WorkflowParam] | None = ...,
        body: collections.abc.Iterable[Global___Statement] | None = ...,
        return_type: builtins.str | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing.Literal["_return_type", b"_return_type", "return_type", b"return_type"],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "_return_type",
            b"_return_type",
            "body",
            b"body",
            "name",
            b"name",
            "params",
            b"params",
            "return_type",
            b"return_type",
        ],
    ) -> None: ...
    def WhichOneof(
        self, oneof_group: typing.Literal["_return_type", b"_return_type"]
    ) -> typing.Literal["return_type"] | None: ...

Global___Workflow: typing_extensions.TypeAlias = Workflow

@typing.final
class ActionDefinition(google.protobuf.message.Message):
    """-----------------------------------------------------------------------------
    Action Definition (for module resolution and signature mapping)
    -----------------------------------------------------------------------------
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    MODULE_FIELD_NUMBER: builtins.int
    PARAM_NAMES_FIELD_NUMBER: builtins.int
    name: builtins.str
    """Action name as registered"""
    module: builtins.str
    """Module where action is defined"""
    @property
    def param_names(
        self,
    ) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """Ordered parameter names for positional mapping"""

    def __init__(
        self,
        *,
        name: builtins.str = ...,
        module: builtins.str | None = ...,
        param_names: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def HasField(
        self, field_name: typing.Literal["_module", b"_module", "module", b"module"]
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "_module",
            b"_module",
            "module",
            b"module",
            "name",
            b"name",
            "param_names",
            b"param_names",
        ],
    ) -> None: ...
    def WhichOneof(
        self, oneof_group: typing.Literal["_module", b"_module"]
    ) -> typing.Literal["module"] | None: ...

Global___ActionDefinition: typing_extensions.TypeAlias = ActionDefinition

@typing.final
class ParseError(google.protobuf.message.Message):
    """-----------------------------------------------------------------------------
    Parse Error
    -----------------------------------------------------------------------------
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MESSAGE_FIELD_NUMBER: builtins.int
    LOCATION_FIELD_NUMBER: builtins.int
    message: builtins.str
    @property
    def location(self) -> Global___SourceLocation: ...
    def __init__(
        self,
        *,
        message: builtins.str = ...,
        location: Global___SourceLocation | None = ...,
    ) -> None: ...
    def HasField(
        self, field_name: typing.Literal["_location", b"_location", "location", b"location"]
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "_location", b"_location", "location", b"location", "message", b"message"
        ],
    ) -> None: ...
    def WhichOneof(
        self, oneof_group: typing.Literal["_location", b"_location"]
    ) -> typing.Literal["location"] | None: ...

Global___ParseError: typing_extensions.TypeAlias = ParseError
