[package]
name = "waymark-extcall-reconciler"
edition = "2024"
version.workspace = true
publish.workspace = true

[dependencies]
waymark-action-core = { workspace = true }
waymark-extcall-reconciler-core = { workspace = true }
waymark-nonzero-duration = { workspace = true }
waymark-vm-driver-core = { workspace = true }
waymark-vm-interpreter-extcallset = { workspace = true }
waymark-vm-runtime-effect = { workspace = true }
waymark-vm-runtime-promise-core = { workspace = true }

nonempty-collections = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt", "sync", "time"] }

[dev-dependencies]
waymark-action-runtime-convert = { workspace = true }
waymark-action-runtime-core = { workspace = true }
waymark-action-runtime-metadata = { workspace = true }
waymark-extcall-reconciler-action-compat = { workspace = true }
waymark-sleep-compat-python = { workspace = true }
waymark-transient-sleep-reconciler = { workspace = true }
waymark-vm-value-python = { workspace = true }
waymark-vm-value-python-convert-proto = { workspace = true }

mockall = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt", "sync", "time"] }
