[package]
name = "waymark-execution-bringup"
edition = "2024"
version.workspace = true
publish.workspace = true

[dependencies]
waymark-action-completions-reconciler = { workspace = true }
waymark-action-completions-reconciler-backend = { workspace = true }
waymark-action-effect-reconciler = { workspace = true }
waymark-action-effect-reconciler-backend = { workspace = true }
waymark-action-runtime-worker-pool = { workspace = true }
waymark-execution-driver = { workspace = true }
waymark-extcall-reconciler = { workspace = true }
waymark-fullset-effect-handler = { workspace = true }
waymark-ids = { workspace = true }
waymark-nonzero-duration = { workspace = true }
waymark-sleep-compat = { workspace = true }
waymark-sleep-reconciler = { workspace = true }
waymark-sleep-reconciler-backend = { workspace = true }
waymark-state-manager = { workspace = true }
waymark-state-vm-executables = { workspace = true }
waymark-state-vm-executables-backend = { workspace = true }
waymark-state-vm-runtimes = { workspace = true }
waymark-state-vm-runtimes-backend = { workspace = true }
waymark-state-vm-runtimes-core = { workspace = true }
waymark-system-vm = { workspace = true, features = ["serde"] }
waymark-vm-codec-rmp = { workspace = true }
waymark-vm-interpreter-fullset = { workspace = true }
waymark-worker-core = { workspace = true }
waymark-workflow-completion = { workspace = true }
waymark-workflow-completion-backend = { workspace = true }
waymark-workload-pinning-backend = { workspace = true }
waymark-workload-pinning-manager = { workspace = true }

chrono = { workspace = true }
tokio = { workspace = true, features = ["sync", "macros", "rt"] }
tokio-util = { workspace = true }
tracing = { workspace = true }

[lib]
doctest = false
