[package]
name = "waymark-action-runtime-worker-pool"
edition = "2024"
version.workspace = true
publish.workspace = true

[dependencies]
waymark-action-runtime-convert = { workspace = true }
waymark-action-runtime-core = { workspace = true }
waymark-action-runtime-metadata = { workspace = true }
waymark-action-runtime-metadata-codec = { workspace = true }
waymark-convert-core = { workspace = true }
waymark-proto = { workspace = true }
waymark-vm-value-convert-core = { workspace = true }
waymark-vm-value-python = { workspace = true }
waymark-worker-core = { workspace = true }

nonempty-collections = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
waymark-action-core = { workspace = true }
waymark-action-runtime-metadata-compat = { workspace = true }
waymark-ids = { workspace = true }

tokio = { workspace = true, features = ["macros", "rt"] }

[lib]
doctest = false
