[package]
name = "waymark-vm-runtime-test"
edition = "2024"
version.workspace = true
publish.workspace = true

[dependencies]
waymark-vm-bytecode = { workspace = true }
waymark-vm-bytecode-core = { workspace = true }
waymark-vm-interpreter = { workspace = true }
waymark-vm-runtime = { workspace = true }
waymark-vm-runtime-core = { workspace = true }

thiserror = { workspace = true }
