'use strict';

const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');

const {
  bootstrapPathForProject,
  bootstrapTypesPathForProject,
  wrapperPathForModule,
  syncActionBootstrap
} = require('../src/compiler/bootstrap.js');

function makeTempProject() {
  return fs.mkdtempSync(path.join(os.tmpdir(), 'waymark-nextjs-bootstrap-'));
}

describe('action bootstrap generation', () => {
  test('writes a stable bootstrap that imports discovered action modules', () => {
    const projectRoot = makeTempProject();
    const actionsDirectory = path.join(projectRoot, 'lib', 'actions');
    fs.mkdirSync(actionsDirectory, { recursive: true });

    fs.writeFileSync(
      path.join(actionsDirectory, 'math.ts'),
      [
        '// use action',
        'export async function double(value) {',
        '  return value * 2;',
        '}',
        ''
      ].join('\n')
    );
    fs.writeFileSync(
      path.join(actionsDirectory, 'ignored.ts'),
      [
        'export async function helper(value) {',
        '  return value;',
        '}',
        ''
      ].join('\n')
    );

    const result = syncActionBootstrap(projectRoot);
    const bootstrapPath = bootstrapPathForProject(projectRoot);
    const typesPath = bootstrapTypesPathForProject(projectRoot);
    const wrapperPath = wrapperPathForModule(projectRoot, 'lib/actions/math.ts');

    expect(result.actionModules.map((entry) => entry.moduleName)).toEqual(['lib/actions/math.ts']);
    expect(fs.readFileSync(bootstrapPath, 'utf8')).toBe(
      [
        '// generated by withWaymark(...)',
        '// imports are project-relative from the bootstrap file',
        '',
        'import "./actions/lib/actions/math.mjs";',
        ''
      ].join('\n')
    );
    expect(fs.readFileSync(wrapperPath, 'utf8')).toBe(
      [
        '// generated by withWaymark(...)',
        'import { __waymarkRegisterAction } from "@waymark/nextjs";',
        'import * as __waymarkModule from "../../../../lib/actions/math.ts";',
        '',
        '__waymarkRegisterAction("lib/actions/math.ts", "double", __waymarkModule.double, ["value"]);',
        ''
      ].join('\n')
    );
    expect(fs.readFileSync(typesPath, 'utf8')).toBe(
      ['// generated by withWaymark(...)', 'export {};', ''].join('\n')
    );
  });
});
