#!/usr/bin/env sh

set -e

bridge=""
worker_id=""

while [ "$#" -gt 0 ]; do
  case "$1" in
    --bridge)
      bridge="$2"
      shift 2
      ;;
    --worker-id)
      worker_id="$2"
      shift 2
      ;;
    --user-module)
      shift 2
      ;;
    *)
      shift 1
      ;;
  esac
done

if [ -n "$bridge" ]; then
  export RAPPEL_BRIDGE_GRPC_ADDR="$bridge"
fi

if [ -n "$worker_id" ]; then
  export RAPPEL_WORKER_ID="$worker_id"
fi

exec node /app/example_app_js/dist/worker.js
