[package]
name = "waymark-backend-postgres"
version.workspace = true
publish.workspace = true
edition = "2024"

[dependencies]
waymark-action-completions-reconciler-backend = { workspace = true }
waymark-action-effect-reconciler-backend = { workspace = true }
waymark-backend-postgres-migrations = { workspace = true }
waymark-backends-core = { workspace = true }
waymark-ids = { workspace = true }
waymark-metrics-util = { workspace = true }
waymark-observability = { workspace = true }
waymark-scheduler-backend = { workspace = true }
waymark-scheduler-core = { workspace = true }
waymark-secret-string = { workspace = true }
waymark-sleep-reconciler-backend = { workspace = true }
waymark-state-vm-executables-backend = { workspace = true }
waymark-state-vm-runtimes-backend = { workspace = true }
waymark-timed-future = { workspace = true }
waymark-vm-runtime-effect = { workspace = true }
waymark-vm-runtime-promise-core = { workspace = true }
waymark-workflow-completion-backend = { workspace = true }
waymark-workflow-service-scheduler-backend = { workspace = true }
waymark-workflow-service-vm-executables-backend = { workspace = true }
waymark-workflow-service-vm-runtimes-backend = { workspace = true }
waymark-workload-pinning-backend = { workspace = true }
waymark-workload-pinning-core = { workspace = true }

chrono = { workspace = true }
function_name = { workspace = true }
metrics = { workspace = true }
nonempty-collections = { workspace = true }
sqlx = { workspace = true, features = ["postgres", "uuid", "chrono", "runtime-tokio"] }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["macros"] }
uuid = { workspace = true }

[dev-dependencies]
waymark-support-test = { workspace = true }

serial_test = { workspace = true }

[lib]
doctest = false
