[package]
name = "waymark-vm-compiler-for-ast-old-test-support"
edition = "2024"
version.workspace = true
publish.workspace = true

[dependencies]
waymark-vm-ast-old = { workspace = true }
waymark-vm-bytecode-core = { workspace = true }
waymark-vm-compiler-for-ast-old-const-value = { workspace = true }
waymark-vm-compiler-for-ast-old-core = { workspace = true }
waymark-vm-instructions-coreset = { workspace = true }
waymark-vm-instructions-extcallset = { workspace = true }
waymark-vm-instructions-pureset = { workspace = true }
waymark-vm-interpreter-operations = { workspace = true }
waymark-vm-interpreter-operations-python = { workspace = true }
waymark-vm-runtime-core = { workspace = true }
waymark-vm-value = { workspace = true }
