[package]
name = "waymark-worker-remote-pool"
edition = "2024"
version.workspace = true
publish.workspace = true

[dependencies]
waymark-managed-process = { workspace = true }
waymark-proto = { workspace = true }
waymark-proto-python-value-conversions = { workspace = true }
waymark-worker-core = { workspace = true }
waymark-worker-process-pool = { workspace = true }
waymark-worker-process-spec = { workspace = true }
waymark-worker-status-core = { workspace = true }

metrics = { workspace = true }
nonempty-collections = { workspace = true }
tokio = { workspace = true, features = ["process"] }
tracing = { workspace = true }
