[package]
name = "waymark-observability-config"
edition = "2024"
version.workspace = true
publish.workspace = true

[dependencies]
waymark-essential-metrics-config = { workspace = true }
waymark-observability-events-config = { workspace = true }
waymark-observability-store-postgres-config = { workspace = true }
waymark-secret-string = { workspace = true }

envfury = { workspace = true }
thiserror = { workspace = true }
