[package]
name = "waymark-vm-compiler-core"
edition = "2024"
version.workspace = true
publish.workspace = true

[dependencies]
waymark-vm-bytecode-core = { workspace = true }
waymark-vm-instructions-coreset = { workspace = true }
waymark-vm-instructions-fullset = { workspace = true }
waymark-vm-instructions-pureset = { workspace = true }
waymark-vm-runtime-core = { workspace = true }
