'use strict';

const fs = require('node:fs');
const path = require('node:path');

const { loadActionExports } = require('./transform.js');

const ACTION_BOOTSTRAP_DIR = '.waymark';
const ACTION_BOOTSTRAP_BASENAME = 'actions-bootstrap';
const ACTION_BOOTSTRAP_FILENAME = `${ACTION_BOOTSTRAP_BASENAME}.mjs`;
const ACTION_BOOTSTRAP_TYPES_FILENAME = `${ACTION_BOOTSTRAP_BASENAME}.d.ts`;
const ACTION_WRAPPERS_DIR = 'actions';
const SOURCE_EXTENSIONS = new Set(['.js', '.jsx', '.ts', '.tsx']);
const EXCLUDED_DIRS = new Set(['.git', '.next', '.waymark', 'node_modules']);

function syncActionBootstrap(projectRoot) {
  const discovered = discoverActionModules(projectRoot);
  const wrapperEntries = syncActionWrappers(projectRoot, discovered.actionModules);
  const bootstrapPath = bootstrapPathForProject(projectRoot);
  const bootstrapSource = renderActionBootstrap(projectRoot, wrapperEntries);
  const typesPath = bootstrapTypesPathForProject(projectRoot);
  const typesSource = renderActionBootstrapTypes();

  const bootstrapChanged = ensureGeneratedFile(bootstrapPath, bootstrapSource);
  const typesChanged = ensureGeneratedFile(typesPath, typesSource);

  return {
    actionModules: discovered.actionModules,
    bootstrapPath,
    changed: bootstrapChanged || typesChanged,
    directories: discovered.directories,
    typesPath
  };
}

function discoverActionModules(projectRoot) {
  const actionCache = new Map();
  const actionModules = [];
  const directories = new Set();

  walkDirectory(projectRoot, projectRoot, actionCache, actionModules, directories);

  actionModules.sort((left, right) => left.moduleName.localeCompare(right.moduleName));

  return {
    actionModules,
    directories: Array.from(directories).sort()
  };
}

function bootstrapPathForProject(projectRoot) {
  return path.join(projectRoot, ACTION_BOOTSTRAP_DIR, ACTION_BOOTSTRAP_FILENAME);
}

function bootstrapTypesPathForProject(projectRoot) {
  return path.join(projectRoot, ACTION_BOOTSTRAP_DIR, ACTION_BOOTSTRAP_TYPES_FILENAME);
}

function walkDirectory(projectRoot, currentDirectory, actionCache, actionModules, directories) {
  directories.add(currentDirectory);

  const entries = fs.readdirSync(currentDirectory, { withFileTypes: true })
    .sort((left, right) => left.name.localeCompare(right.name));

  for (const entry of entries) {
    if (entry.isSymbolicLink()) {
      continue;
    }

    const entryPath = path.join(currentDirectory, entry.name);

    if (entry.isDirectory()) {
      if (EXCLUDED_DIRS.has(entry.name)) {
        continue;
      }
      walkDirectory(projectRoot, entryPath, actionCache, actionModules, directories);
      continue;
    }

    if (!isSupportedSourceFile(entry.name)) {
      continue;
    }

    const source = fs.readFileSync(entryPath, 'utf8');
    if (!source.includes('use action')) {
      continue;
    }

    const actionExports = loadActionExports(entryPath, projectRoot, actionCache);
    if (actionExports.size === 0) {
      continue;
    }

    const actions = Array.from(actionExports.values());
    actionModules.push({
      actions: actions.map((action) => ({
        actionName: action.actionName,
        paramNames: action.paramNames
      })),
      moduleName: actions[0].moduleName,
      resourcePath: entryPath,
      wrapperPath: wrapperPathForModule(projectRoot, actions[0].moduleName)
    });
  }
}

function isSupportedSourceFile(filename) {
  if (filename.endsWith('.d.ts')) {
    return false;
  }

  return SOURCE_EXTENSIONS.has(path.extname(filename));
}

function renderActionBootstrap(projectRoot, wrapperEntries) {
  const bootstrapDirectory = path.dirname(bootstrapPathForProject(projectRoot));
  const lines = [
    '// generated by withWaymark(...)',
    '// imports are project-relative from the bootstrap file',
    ''
  ];

  for (const wrapperEntry of wrapperEntries) {
    lines.push(`import "${importPathForModule(bootstrapDirectory, wrapperEntry.wrapperPath)}";`);
  }

  lines.push('');
  return lines.join('\n');
}

function renderActionBootstrapTypes() {
  return ['// generated by withWaymark(...)', 'export {};', ''].join('\n');
}

function importPathForModule(fromDirectory, targetPath) {
  const relativePath = path.relative(fromDirectory, targetPath).split(path.sep).join('/');
  if (relativePath.startsWith('.')) {
    return relativePath;
  }
  return `./${relativePath}`;
}

function wrappersDirectoryForProject(projectRoot) {
  return path.join(projectRoot, ACTION_BOOTSTRAP_DIR, ACTION_WRAPPERS_DIR);
}

function wrapperPathForModule(projectRoot, moduleName) {
  const extension = path.extname(moduleName);
  const withoutExtension = extension ? moduleName.slice(0, -extension.length) : moduleName;
  const segments = withoutExtension.split('/').filter(Boolean);
  return path.join(wrappersDirectoryForProject(projectRoot), ...segments) + '.mjs';
}

function syncActionWrappers(projectRoot, actionModules) {
  const wrappersDirectory = wrappersDirectoryForProject(projectRoot);
  fs.rmSync(wrappersDirectory, { force: true, recursive: true });

  const wrapperEntries = [];
  for (const actionModule of actionModules) {
    const source = renderActionWrapper(projectRoot, actionModule);
    ensureGeneratedFile(actionModule.wrapperPath, source);
    wrapperEntries.push({
      moduleName: actionModule.moduleName,
      wrapperPath: actionModule.wrapperPath
    });
  }

  return wrapperEntries;
}

function renderActionWrapper(projectRoot, actionModule) {
  const wrapperDirectory = path.dirname(actionModule.wrapperPath);
  const lines = [
    '// generated by withWaymark(...)',
    'import { __waymarkRegisterAction } from "@waymark/nextjs";',
    `import * as __waymarkModule from "${importPathForModule(wrapperDirectory, actionModule.resourcePath)}";`,
    ''
  ];

  for (const action of actionModule.actions) {
    lines.push(
      `__waymarkRegisterAction(${JSON.stringify(actionModule.moduleName)}, ${JSON.stringify(action.actionName)}, __waymarkModule.${action.actionName}, ${JSON.stringify(action.paramNames)});`
    );
  }

  lines.push('');
  return lines.join('\n');
}

function ensureGeneratedFile(filePath, nextContents) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });

  const existingContents = fs.existsSync(filePath) ? fs.readFileSync(filePath, 'utf8') : null;
  if (existingContents === nextContents) {
    return false;
  }

  fs.writeFileSync(filePath, nextContents, 'utf8');
  return true;
}

module.exports = {
  ACTION_BOOTSTRAP_FILENAME,
  ACTION_BOOTSTRAP_TYPES_FILENAME,
  bootstrapPathForProject,
  bootstrapTypesPathForProject,
  discoverActionModules,
  wrapperPathForModule,
  syncActionBootstrap
};
