'use strict';

const fs = require('node:fs');
const path = require('node:path');

const { loadActionExports } = require('./transform.js');

const ACTION_BOOTSTRAP_DIR = '.waymark';
const ACTION_BOOTSTRAP_BASENAME = 'actions-bootstrap';
const ACTION_BOOTSTRAP_FILENAME = `${ACTION_BOOTSTRAP_BASENAME}.mjs`;
const ACTION_BOOTSTRAP_TYPES_FILENAME = `${ACTION_BOOTSTRAP_BASENAME}.d.ts`;
const SOURCE_EXTENSIONS = new Set(['.js', '.jsx', '.ts', '.tsx']);
const EXCLUDED_DIRS = new Set(['.git', '.next', '.waymark', 'node_modules']);

function syncActionBootstrap(projectRoot) {
  const discovered = discoverActionModules(projectRoot);
  const bootstrapPath = bootstrapPathForProject(projectRoot);
  const bootstrapSource = renderActionBootstrap(projectRoot, discovered.actionModules);
  const typesPath = bootstrapTypesPathForProject(projectRoot);
  const typesSource = renderActionBootstrapTypes();

  const bootstrapChanged = ensureGeneratedFile(bootstrapPath, bootstrapSource);
  const typesChanged = ensureGeneratedFile(typesPath, typesSource);

  return {
    actionModules: discovered.actionModules,
    bootstrapPath,
    changed: bootstrapChanged || typesChanged,
    directories: discovered.directories,
    typesPath
  };
}

function discoverActionModules(projectRoot) {
  const actionCache = new Map();
  const actionModules = [];
  const directories = new Set();

  walkDirectory(projectRoot, projectRoot, actionCache, actionModules, directories);

  actionModules.sort((left, right) => left.moduleName.localeCompare(right.moduleName));

  return {
    actionModules,
    directories: Array.from(directories).sort()
  };
}

function bootstrapPathForProject(projectRoot) {
  return path.join(projectRoot, ACTION_BOOTSTRAP_DIR, ACTION_BOOTSTRAP_FILENAME);
}

function bootstrapTypesPathForProject(projectRoot) {
  return path.join(projectRoot, ACTION_BOOTSTRAP_DIR, ACTION_BOOTSTRAP_TYPES_FILENAME);
}

function walkDirectory(projectRoot, currentDirectory, actionCache, actionModules, directories) {
  directories.add(currentDirectory);

  const entries = fs.readdirSync(currentDirectory, { withFileTypes: true })
    .sort((left, right) => left.name.localeCompare(right.name));

  for (const entry of entries) {
    if (entry.isSymbolicLink()) {
      continue;
    }

    const entryPath = path.join(currentDirectory, entry.name);

    if (entry.isDirectory()) {
      if (EXCLUDED_DIRS.has(entry.name)) {
        continue;
      }
      walkDirectory(projectRoot, entryPath, actionCache, actionModules, directories);
      continue;
    }

    if (!isSupportedSourceFile(entry.name)) {
      continue;
    }

    const source = fs.readFileSync(entryPath, 'utf8');
    if (!source.includes('use action')) {
      continue;
    }

    const actionExports = loadActionExports(entryPath, projectRoot, actionCache);
    if (actionExports.size === 0) {
      continue;
    }

    const firstAction = actionExports.values().next().value;
    actionModules.push({
      moduleName: firstAction.moduleName,
      resourcePath: entryPath
    });
  }
}

function isSupportedSourceFile(filename) {
  if (filename.endsWith('.d.ts')) {
    return false;
  }

  return SOURCE_EXTENSIONS.has(path.extname(filename));
}

function renderActionBootstrap(projectRoot, actionModules) {
  const bootstrapDirectory = path.dirname(bootstrapPathForProject(projectRoot));
  const lines = [
    '// generated by withWaymark(...)',
    '// imports are project-relative from the bootstrap file',
    ''
  ];

  for (const actionModule of actionModules) {
    lines.push(`import "${importPathForModule(bootstrapDirectory, actionModule.resourcePath)}";`);
  }

  lines.push('');
  return lines.join('\n');
}

function renderActionBootstrapTypes() {
  return ['// generated by withWaymark(...)', 'export {};', ''].join('\n');
}

function importPathForModule(fromDirectory, targetPath) {
  const relativePath = path.relative(fromDirectory, targetPath).split(path.sep).join('/');
  if (relativePath.startsWith('.')) {
    return relativePath;
  }
  return `./${relativePath}`;
}

function ensureGeneratedFile(filePath, nextContents) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });

  const existingContents = fs.existsSync(filePath) ? fs.readFileSync(filePath, 'utf8') : null;
  if (existingContents === nextContents) {
    return false;
  }

  fs.writeFileSync(filePath, nextContents, 'utf8');
  return true;
}

module.exports = {
  ACTION_BOOTSTRAP_FILENAME,
  ACTION_BOOTSTRAP_TYPES_FILENAME,
  bootstrapPathForProject,
  bootstrapTypesPathForProject,
  discoverActionModules,
  syncActionBootstrap
};
