[package]
name = "waymark-vm-runtime-core"
edition = "2024"
version.workspace = true
publish.workspace = true

[dependencies]
waymark-typed-vec-serde = { workspace = true, optional = true }
waymark-vm-exception-handler = { workspace = true }
waymark-vm-runtime-effect = { workspace = true }
waymark-vm-runtime-exception = { workspace = true }
waymark-vm-runtime-promise-core = { workspace = true }

index_type = { workspace = true }
serde = { workspace = true, optional = true }
thiserror = { workspace = true }

[features]
default = []

serde = [
  "dep:serde",
  "dep:waymark-typed-vec-serde",
  "waymark-vm-exception-handler/serde",
  "waymark-vm-runtime-effect/serde",
  "waymark-vm-runtime-exception/serde",
  "waymark-vm-runtime-promise-core/serde",
]

[dev-dependencies]
waymark-vm-runtime-promise-value = { workspace = true }
waymark-vm-runtime-value = { workspace = true }
