[package]
name = "waymark-vm-interpreter-operations-python"
edition = "2024"
version.workspace = true
publish.workspace = true

[dependencies]
waymark-vm-exception-type-ids = { workspace = true }
waymark-vm-instructions-pureset = { workspace = true }
waymark-vm-interpreter-coreset = { workspace = true }
waymark-vm-interpreter-pureset = { workspace = true }
waymark-vm-runtime-exception = { workspace = true }
waymark-vm-value = { workspace = true }

thiserror = { workspace = true }
typed_floats = { workspace = true }

[dev-dependencies]
waymark-vm-interpreter-operations = { workspace = true }
waymark-vm-runtime-exception = { workspace = true }
waymark-vm-runtime-promise-core = { workspace = true }

indexmap = { workspace = true }
