//! Composite interpreter machinery.
//!
//! A composite interpreter implements `waymark_vm_interpreter::Interpreter`
//! by delegating to a set of sub-interpreters, one per instruction set:
//! instruction dispatch routes each combined-instruction variant to its
//! sub-interpreter, and the hooks run the sub-interpreters in sequence,
//! chaining while the frame stays in the same state.
//!
//! The [`Interpreter`] derive generates that implementation from a struct
//! whose fields are the sub-interpreters; see the derive's documentation
//! for the attribute surface. The machinery is independent of any concrete
//! runtime: the structural operations it needs are expressed through
//! the vocabulary traits, which the runtime crates implement for their
//! own types by depending on `waymark-vm-interpreter-composite-core`
//! directly.

#![warn(missing_docs)]

pub use waymark_vm_interpreter_composite_macros::Interpreter;

/// Dependencies of the code generated by the [`Interpreter`] derive.
///
/// Not public API: the derive resolves its generated references through
/// this module so that deriving crates need only this crate as
/// a dependency.
#[doc(hidden)]
pub mod __hidden {
    pub use waymark_vm_interpreter;
    pub use waymark_vm_interpreter_composite_core;
    pub use waymark_vm_runtime_view_capture;
}

/// Continue the hook chain only when the sub-interpreter yielded
/// [`waymark_vm_interpreter::ExecutionOutcome::Continue`] without moving
/// the frame to a different state; otherwise the chain is done and
/// the outcome is final.
pub fn chain<Frame, Effect>(
    state_token: Frame::StateToken,
    outcome: waymark_vm_interpreter::ExecutionOutcome<Frame, Effect>,
) -> core::ops::ControlFlow<waymark_vm_interpreter::ExecutionOutcome<Frame, Effect>, Frame>
where
    Frame: waymark_vm_interpreter_composite_core::DetectStateSwitch,
{
    match outcome {
        waymark_vm_interpreter::ExecutionOutcome::Continue(frame)
            if !waymark_vm_interpreter_composite_core::DetectStateSwitch::state_switched(
                &frame,
                &state_token,
            ) =>
        {
            core::ops::ControlFlow::Continue(frame)
        }
        outcome => core::ops::ControlFlow::Break(outcome),
    }
}
