[package]
name = "waymark-observability-bringup"
edition = "2024"
version.workspace = true
publish.workspace = true

[dependencies]
waymark-essential-metrics-bringup = { workspace = true }
waymark-essential-metrics-sampler = { workspace = true }
waymark-ids = { workspace = true }
waymark-observability-config = { workspace = true }
waymark-observability-store-postgres = { workspace = true }
waymark-observability-store-postgres-bringup = { workspace = true }
waymark-observability-store-postgres-migrations = { workspace = true }

sqlx = { workspace = true, features = ["migrate"] }
thiserror = { workspace = true }
tokio-util = { workspace = true }
