[package]
name = "waymark-vm-interpreter-fullset"
edition = "2024"
version.workspace = true
publish.workspace = true

[dependencies]
waymark-vm-executable = { workspace = true }
waymark-vm-instructions-coreset = { workspace = true }
waymark-vm-instructions-extcallset = { workspace = true }
waymark-vm-instructions-fullset = { workspace = true }
waymark-vm-instructions-pureset = { workspace = true }
waymark-vm-interpreter = { workspace = true }
waymark-vm-interpreter-coreset = { workspace = true }
waymark-vm-interpreter-extcallset = { workspace = true }
waymark-vm-interpreter-pureset = { workspace = true }
waymark-vm-runtime-core = { workspace = true }
waymark-vm-runtime-promise-core = { workspace = true }

derive-where = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
waymark-nonzero-duration = { workspace = true }
waymark-vm-runtime = { workspace = true }
waymark-vm-runtime-promise-value = { workspace = true }
waymark-vm-runtime-test = { workspace = true }
waymark-vm-runtime-value = { workspace = true }
