[package]
name = "waymark-transient-execution-bringup"
edition = "2024"
version.workspace = true
publish.workspace = true

[dependencies]
waymark-action-runtime-convert = { workspace = true }
waymark-action-runtime-core = { workspace = true }
waymark-action-runtime-metadata = { workspace = true }
waymark-convert-core = { workspace = true }
waymark-extcall-reconciler = { workspace = true }
waymark-extcall-reconciler-action-compat = { workspace = true }
waymark-fullset-effect-handler = { workspace = true }
waymark-sleep-compat-python = { workspace = true }
waymark-system-vm = { workspace = true, features = ["serde"] }
waymark-transient-sleep-reconciler = { workspace = true }
waymark-vm-ast-old = { workspace = true }
waymark-vm-bytecode-core = { workspace = true }
waymark-vm-codec-rmp = { workspace = true }
waymark-vm-compiler-for-ast-old = { workspace = true }
waymark-vm-driver = { workspace = true }
waymark-vm-driver-core = { workspace = true, features = ["tokio"] }
waymark-vm-driver-thread = { workspace = true }
waymark-vm-runtime = { workspace = true }
waymark-vm-runtime-builder = { workspace = true }
waymark-vm-runtime-exception = { workspace = true }
waymark-workflow-completion-core = { workspace = true }
waymark-workflow-completion-direct = { workspace = true }

thiserror = { workspace = true }
tokio = { workspace = true, features = ["sync"] }
tokio-util = { workspace = true }

[lib]
doctest = false
