[package]
name = "waymark-retention-sweeper"
edition = "2024"
version.workspace = true
publish.workspace = true

[dependencies]
waymark-nonzero-duration = { workspace = true }

chrono = { workspace = true, default-features = false, features = ["clock"] }
tokio = { workspace = true, features = ["macros", "time"] }
tracing = { workspace = true }
