[package]
name = "waymark-action-effect-reconciler-backend"
edition = "2024"
version.workspace = true
publish.workspace = true

[dependencies]
waymark-vm-runtime-effect = { workspace = true }
waymark-vm-runtime-promise-core = { workspace = true }

nonempty-collections = { workspace = true }

[lib]
doctest = false
