[package]
name = "waymark-http-webapp"
edition = "2024"
version.workspace = true
publish.workspace = true

[dependencies]
waymark-webapp-assets = { workspace = true }

axum = { workspace = true }

[dev-dependencies]
http-body-util = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tower = { workspace = true, features = ["util"] }

[lib]
doctest = false
