[package]
name = "waymark-action-runtime-convert"
edition = "2024"
version.workspace = true
publish.workspace = true

[dependencies]
waymark-action-runtime-core = { workspace = true }
waymark-convert-core = { workspace = true }
waymark-proto = { workspace = true }
waymark-proto-message-conversions = { workspace = true }
waymark-proto-python-value-conversions = { workspace = true }
waymark-vm-runtime-exception = { workspace = true }
waymark-vm-value-convert-core = { workspace = true }
waymark-vm-value-convert-json = { workspace = true }
waymark-vm-value-python = { workspace = true }
waymark-worker-core = { workspace = true }
