[package]
name = "waymark-action-runtime-convert"
edition = "2024"
version.workspace = true
publish.workspace = true

[dependencies]
waymark-action-runtime-core = { workspace = true }
waymark-action-runtime-metadata-codec = { workspace = true }
waymark-convert-core = { workspace = true }
waymark-proto = { workspace = true }
waymark-proto-python-value-conversions = { workspace = true }
waymark-vm-value-convert-core = { workspace = true }
waymark-vm-value-python = { workspace = true }
waymark-vm-value-python-convert-proto = { workspace = true }

indexmap = { workspace = true }
prost = { workspace = true }
thiserror = { workspace = true }
