[package]
name = "waymark-transient-sleep-reconciler"
edition = "2024"
version.workspace = true
publish.workspace = true

[dependencies]
waymark-extcall-reconciler-core = { workspace = true }
waymark-nonzero-duration = { workspace = true }
waymark-sleep-core = { workspace = true }
waymark-vm-driver-core = { workspace = true }
waymark-vm-runtime-promise-core = { workspace = true }

nonempty-collections = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt", "sync", "time"] }
tracing = { workspace = true }

[dev-dependencies]
waymark-sleep-compat = { workspace = true }
waymark-vm-value = { workspace = true }

tokio = { workspace = true, features = ["macros", "rt", "sync", "time"] }
