[package]
name = "waymark-task-supervisor"
edition = "2024"
version.workspace = true
publish.workspace = true

[dependencies]
waymark-managed-spawner = { workspace = true }

futures-util = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt", "sync", "tracing"] }
tokio-util = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
insta = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt", "sync"] }
